#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Make 3D mesh in slab of cells.
#cd wingMotion1_snappyHexMesh
#runApplication blockMesh
#runApplication snappyHexMesh -overwrite

# Make a 2D mesh by extruding a patch and solve to steady state.
#cd ../simplescaled
runApplication extrudeMesh
runApplication createPatch -overwrite
cp -r 0.org 0
runApplication simpleFoam

# Copy the mesh from the steady state case and map the results to a
# mesh motion case, then solve transient.

# ----------------------------------------------------------------- end-of-file
