#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ../simpleOutlets/constant/polyMesh/* constant/polyMesh/
cp -r 0.org 0
foamJob decomposePar
foamJob -s -p moveMesh
foamJob reconstructPar
# ----------------------------------------------------------------- end-of-file
