#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r ../simple/constant/polyMesh/* constant/polyMesh/
#runApplication extrudeMesh
#runApplication createPatch -overwrite
cp -r 0.org 0
runApplication mapFields ../simple -sourceTime latestTime -consistent
mv 0/pointDisplacement.unmapped 0/pointDisplacement
#runApplication decomposePar
#runParallel `getApplication` 4
pimpleDyMFoam
#runApplication reconstructPar
#rm -r processor*
# ----------------------------------------------------------------- end-of-file
