#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

#runApplication extrudeMesh
#runApplication createPatch -overwrite
cp -r ../simpleOutlets/constant/polyMesh/* constant/polyMesh/
cp -r 0.org 0
runApplication mapFields ../simpleOutlets -sourceTime latestTime -consistent
mv 0/pointDisplacement.unmapped 0/pointDisplacement
runApplication decomposePar
runParallel `getApplication` 4
runApplication reconstructPar
rm -r processor*
# ----------------------------------------------------------------- end-of-file
